### ISSUE TITLE
Check if events are flowing according d3 concept

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#29]

**Comment by larsvers** [comment]
If all the data was in the client, I probably would make use of the D3 lifecycle to not only enter but also update and exit the data (the triangle markers would then have to be wired up slightly differently). However, the way the app is - sensibly - build, the current flow seems fine. 

One thought would be to leverage a data update on brush rather than a round-trip to the server. This would make the update on brush more fluid but would potentially have implications on the search list and their triangle markers.
